export default {
    "login": "rubcode",
    "id": 18094542,
    "node_id": "MDQ6VXNlcjE4MDk0NTQy",
    "avatar_url": "https://avatars.githubusercontent.com/u/18094542?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rubcode",
    "html_url": "https://github.com/rubcode",
    "followers_url": "https://api.github.com/users/rubcode/followers",
    "following_url": "https://api.github.com/users/rubcode/following{/other_user}",
    "gists_url": "https://api.github.com/users/rubcode/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rubcode/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rubcode/subscriptions",
    "organizations_url": "https://api.github.com/users/rubcode/orgs",
    "repos_url": "https://api.github.com/users/rubcode/repos",
    "events_url": "https://api.github.com/users/rubcode/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rubcode/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Rub Rivero",
    "company": "Telmex",
    "blog": "http://www.rubrivero.com/",
    "location": "CDMX, Mexio",
    "email": null,
    "hireable": null,
    "bio": "Web Developer with experience in Js, React, PHP and an eternal student of Python and Data Scients\r\n",
    "twitter_username": "rubyrubyy",
    "public_repos": 16,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2016-03-27T01:41:37Z",
    "updated_at": "2024-09-10T19:35:24Z"
  }